### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by brokedev**

### CODE REVIEW

**Comment by brokedev** [comment]
Fix a few mistakes

**Comment by xamionex** [comment]
Why did you remove every formatting though?
I get fixing my spelling mistakes but don't remove buttons for no reason
This is your build:
https://brokedev.steamskins.pages.dev/guides/installation/

**Comment by brokedev** [comment]
It doesn't show it properly for me

**Comment by brokedev** [comment]
There should be a seperate repo between the website and GitHub so people don't get confused on "why is the link so long?"

**Comment by xamionex** [comment]
> There should be a seperate repo between the website and GitHub so people don't get confused on "why is the link so long?"

The site is steamskins.pages.dev
The repo for that is on github (here)
The reason you don't see formatting is because you're editing it, wouldn't make sense if you couldn't see how it's written, unless you're viewing the site and it doesn't display there, them it's an issue with retype

**Comment by xamionex** [comment]
Closing due to no reply

**Pull request closed without merging**
